dataset:
  train_dataset_path: "/Users/waihongong/github/assignment1-basics/data/TinyStoriesTrain_10k/TinyStoriesV2-GPT4-valid.tok.npy"
  valid_dataset_path: "/Users/waihongong/github/assignment1-basics/data/TinyStoriesTrain_10k/TinyStoriesV2-GPT4-valid.tok.npy"
  vocab_path: "tests/fixtures/gpt2_vocab.json"
device: "mps"
ckpt_dir: "checkpoints"
ckpt_every: 20
training:
  num_tokens: 100000
  valid_num_tokens: 3270
  batch_size: 32
  context_length: 100
model:
  num_heads: 4
  d_head: 32
  d_ff: 384