dataset:
  train_dataset_path: "/home/ong/personal/standford-cs336-2025/assignment1-basics/data/TinyStoriesV2-GPT4-train.tok.npy"
  valid_dataset_path: "/home/ong/personal/standford-cs336-2025/assignment1-basics/data/TinyStoriesV2-GPT4-valid.tok.npy"
  vocab_path: "tests/fixtures/gpt2_vocab.json"
device: "cuda"
ckpt_dir: "checkpoints"
ckpt_every: 20
training:
  num_tokens: 327000
  valid_num_tokens: 3270
model:
  num_heads: 4
  d_head: 32
  d_ff: 384