dataset:
  train_dataset_path: "/content/drive/MyDrive/colab_data/cs336_assignment1/TinyStoriesTrain_10k/TinyStoriesV2-GPT4-valid-small.tok.npy"
  valid_dataset_path: "/content/drive/MyDrive/colab_data/cs336_assignment1/TinyStoriesTrain_10k/TinyStoriesV2-GPT4-valid-small.tok.npy"
  vocab_path: "/content/drive/MyDrive/colab_data/cs336_assignment1/TinyStoriesTrain_10k/vocab.json"
  merges_path: "/content/drive/MyDrive/colab_data/cs336_assignment1/TinyStoriesTrain_10k/merges.txt"
device: "cuda"
ckpt_dir: "/content/drive/MyDrive/colab_data/cs336_assignment1/experiment_ckpts/remote_test"
ckpt_every: 20
training:
  num_tokens: 1000000
  valid_num_tokens: 32700
model:
  num_heads: 16
  d_head: 32
  d_ff: 1344